### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by koppen** [mtolbol/sharetribe#13]
Stripe skal bruges som betalingsudbyder til betaling af ydelser som bookes af end-users. Betaling fra end-users går via Stripe og til Tumlino, hvorefter disse sendes til udbyderne efter udført behandling.

Løsning:  Stripe opsættes som betalingsløsning (Std. integration i Sharetribe)

**Comment by mtolbol** [comment]
Test data skak sættes op på Beta.Tumlino.dk

**Comment by koppen** [comment]
Jeg har slået Stripe-integrationen til på beta nu, så du bør kunne indtaste API nøgler på https://beta.tumlino.dk/da-DK/admin/payment_preferences - og generelt konfigurere gebyrer m.m.

Hvis du allerede nu har produktions/live-nøgler ville de være mest oplagte naturligvis, men ellers må vi nøjes med test-nøglerne indtil videre.

**Comment by mtolbol** [comment]
Hej Jakob,
Jeg har forsøgt at sætte op med test API nøgler hentet fra Stripe, men Sharetribe vil ikke godtage disse.

Jeg har ikke Live API nøgler endnu, men jeg forventer at vi har dem i løbet af denne eller næste uge. Så måske det er fint at vente til vi har Live nøgler, for at gøre det lettest.

Mvh.

**Comment by koppen** [comment]
Ugh, det ser ud til at Sharetribe som udgangspunkt ikke vil spise test-nøglerne i production. Jeg tænker vi er nødt til at afvente live-nøglerne så 😞
