### ISSUE TITLE
Håndtering af subscription

### ISSUE THREAD

**Issue by koppen** [mtolbol/sharetribe#14]
Tumlino’s forretningsmodel baseres på subscription fra vores udbydere. Tumlino’s platform skal derfor kunne håndteres disse månedlige subscription. Hvorvidt Stripe, ChargeBee eller anden udbyder vælges til dette er ikke afgørende for Tumlino. Kan Stripe håndtere dette, vil det foretrækkes at vi benytter samme betalingsudbyder til at håndterer månedlige betalinger fra udbydere

Løsning: Stripe, ChargeBee eller anden aktør opsættes til håndtering af subscription fra udbydere

**Comment by mtolbol** [comment]
Håndteres manuelt i fase 1
