### ISSUE TITLE
Side til forretningsbetingelser

### ISSUE THREAD

**Issue by koppen** [mtolbol/sharetribe#16]
Der bør indsættes en side til forretningsbetingelser. Tumlino leverer forretningsbetingelser (tekst), som indsættes på siden. Siden skal ydermere have et menupunkt i både top menu og footer.

Forretningsbetingelser er vedhæftet i Bilag 1

Løsning: Side til forretningsbetingelser, med adgang fra topmenu og footer

* [x] Side med forretningsbetingelser
* [ ] Adgang fra topmenu
* [ ] Adgang fra footer
* [ ] Ret telefonnummer fra `XX XX XX XX`

**Comment by mtolbol** [comment]
Vi forsøger som udgangspunkt at bruge den standard page (privatliv & brugervilkår) der ligger i Sharetribe
