### ISSUE TITLE
Cookie godkendelse

### ISSUE THREAD

**Issue by koppen** [mtolbol/sharetribe#22]
Når en bruger lander på Tumlino.dk, skal der fremkomme et pop-up vindue hvor brugeren kan godkende brug af cookies

**Comment by koppen** [comment]
En mulig, nem'ish løsning her, kunne være at basere sig www.cookiebot.com

**Comment by mtolbol** [comment]
@koppen Lad os afprøve cookiebot.com - jeg går ud fra at vi med nuværende setup kan starte ud med gratis versionen? Men efter markedspladsen fyldes op, vil de 100 undersider sikkert hurtigt blive fyldt.

Hvis du har gode erfaringer med cookiebot.com opsætter vi denne - du kan selv vurdere hvorvidt vi skal starte på gratis versionen eller blot tage premium small fra start.

**Comment by koppen** [comment]
Cookiebot er hvertfald nem at integrere, og har en del muligheder for at lave tilpasninger. Og ja, vi bør kunne starte med den gratis version.

**Comment by mtolbol** [comment]
Helt fint - Vi kører med cookiebot :)

**Comment by koppen** [comment]
Jeg har oprettet en gratis konto hos Cookiebot og integreret den; afventer pt på at de får scannet vores cookies:

![Screenshot 2019-07-25 09 39 19](https://user-images.githubusercontent.com/6480/61855329-2a692b00-aec0-11e9-9fde-67b8369cc896.png)

Jeg har sendt adgangskode m.m. til dig, @mtolbol
