### ISSUE TITLE
Søgebar virker ikke

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#30]
Uanset hvad der søges på i søgebaren findes ingen resultater

![søgebar - error](https://user-images.githubusercontent.com/44906533/60804886-e3b8c880-a17e-11e9-8c45-a0959038b284.PNG)

**Comment by koppen** [comment]
Det ser ud til at fungere nu, hvertfald giver både "amning" og "babyer" resultater:

* [amning](https://beta.tumlino.dk/s?category=all&view=grid&q=amning&price_min=0&price_max=100000)
* [babyer](https://beta.tumlino.dk/s?category=all&view=grid&q=babyer&price_min=0&price_max=100000)

Det er muligt, at det er den nylige deploy, der har fixet noget, dog, og vi bør være opmærksomme på, om problemet opstår igen.
