### ISSUE TITLE
Kategorier kobles ikke op på annoncer

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#31]
Kategorierne kobles ikke korrekt op på annoncerne, selvom de vælges ved oprettelse af annoncen.

Det betyder at filteret på markedspladsen ikke fungerer.

![Kategorier - error](https://user-images.githubusercontent.com/44906533/60805055-575ad580-a17f-11e9-8798-8d4c4f0c08e9.PNG)

**Comment by koppen** [comment]
Det ser ud til at fungere nu:

![categories](https://user-images.githubusercontent.com/6480/61797507-d0b52200-ae27-11e9-833a-c62594d97c4a.gif)

Jeg forestiller mig, at dette er en duplikat af #30, da skift af kategorier "bare" resulterer i en ny søgning.
