### ISSUE TITLE
Link til "Burgervilkår" ved oprettelse af af profil, virker ikke.

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#32]
Link til   "Burgervilkår" ved oprettelse af af profil, virker ikke.   Re-directer til samme side / Side med oprettelse

Ved oprettelse af en ny profil, er der mulighed for at tilgå "brugervilkår", men dette link fungerer ikke. Linket re-dicreter blot til den side man står på = "tilmeldings siden".

![Brugervilkår - Error](https://user-images.githubusercontent.com/44906533/60811288-37cba900-a18f-11e9-9491-b8ece06347a6.PNG)

**Comment by koppen** [comment]
Jeg kan ikke genskabe problemet. Her er hvad jeg gør:

1. Gå til https://beta.tumlino.dk/da-DK/signup
2. Klik på "Brugervilkår"

Resultat:

![terms](https://user-images.githubusercontent.com/6480/61797704-386b6d00-ae28-11e9-844b-edc61622483c.gif)

Oplever du noget andet pt, @mtolbol ?
