### ISSUE TITLE
Google Maps API - fejl på annoncer

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#40]
Når man går ind på en annonce er der en fejl på Google Maps API'et:

![Skærmbillede 2019-07-29 kl  22 02 08](https://user-images.githubusercontent.com/44906533/62078444-f63d9380-b24c-11e9-86df-e8cd7829cc2f.png)

**Comment by koppen** [comment]
Der manglede adgang til [Maps Static API'et](https://console.developers.google.com/google/maps-apis/apis/static-maps-backend.googleapis.com/metrics?authuser=1&folder=&organizationId=&project=tumlino&duration=P30D). Det har jeg enabled, og dokumenteret de krævede API'er i https://github.com/mtolbol/sharetribe/commit/2d12aab7e5b4fdd7bc99101e581f1ddb76557954#diff-ab4cb539ea1f53a62601a060ce058aafR11.

Nu ser det bedre ud:

![Screenshot 2019-07-30 09 55 15](https://user-images.githubusercontent.com/6480/62112995-15bbd700-b2b4-11e9-85b7-6fbf23a66a39.png)

**Comment by mtolbol** [comment]
@koppen Hos mig ser dette forsat ikke ud til at virke. Samme fejl-besked som tidligere på annoncer

**Comment by koppen** [comment]
Jeg har tilføjet [Maps Embed API](https://console.cloud.google.com/google/maps-apis/apis/maps-embed-backend.googleapis.com/metrics?authuser=1&project=tumlino) og det ser ud til at løse problemet.

Jeg undrer mig over, om jeg monstro har fjernet lidt for meget i en oprydning efter at have haft det til at fungere sidst.

**Comment by mtolbol** [comment]
Helt O.K - burde det være deployet til sitet nu?

---
Med venlig hilsen / Kind regards

Morten Tølbøl Sørensen

+45 6013 1056
m@tolbol.dk 

Jakob Skjerning skrev den 15.08.2019 10:42:

> Jeg har tilføjet Maps Embed API [1] og det ser ud til at løse problemet. 
> 
> Jeg undrer mig over, om jeg monstro har fjernet lidt for meget i en oprydning efter at have haft det til at fungere sidst. 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://console.cloud.google.com/google/maps-apis/apis/maps-embed-backend.googleapis.com/metrics?authuser=1&amp;project=tumlino
[2]
https://github.com/mtolbol/sharetribe/issues/40?email_source=notifications&amp;email_token=AKWTQJKEKP53XFWOUOSWXDLQEUJG7A5CNFSM4IHVYONKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4LG63Y#issuecomment-521564015
[3]

**Comment by koppen** [comment]
Jamen, hvad sker der? Nu virker det ikke igen? Jeg sværger at jeg kunne se kortet i går, men nu giver den samme fejl igen: https://beta.tumlino.dk/da-DK/listings/18-akupunktur-til-babyer :(

Hvor ville det være rart, hvis Google gad fortælle hvilken service eller API nøglen ikke er authorized til, så vi ikke behøver gætte :o/

**Comment by koppen** [comment]
arg, der er 2 steder, man skal enable API'er, og hvis man glemmer det ene sted virker det åbenbart alligevel et kort stykke tid 😡 Nuvel, vi prøver igen...

Fixet:

![Screenshot 2019-08-16 11 37 55](https://user-images.githubusercontent.com/6480/63158787-53419380-c01a-11e9-8585-e929ec961941.png)
![Screenshot 2019-08-16 11 38 01](https://user-images.githubusercontent.com/6480/63158788-53da2a00-c01a-11e9-89b0-ec019ebeba52.png)

**Comment by mtolbol** [comment]
@koppen - Det virker her hos mig nu også :) Godt arbejde
