### ISSUE TITLE
Problem / Fejl ved søgning og kategorier

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#41]
Forsat fejl ved søgning og kategorier. Det ser ud til at virke på "gamle" annoncer, men ved oprettelse af en ny annonce, kaldet "Baby Tumling" og placeret under kategorien "Tumling". Denne annonce kan hverken søges frem via søgefunktionen, eller filtreres ved hjælp af kategori-filteret "tumling".

[Fejl på søgning og filter.zip](https://github.com/mtolbol/sharetribe/files/3444129/Fejl.pa.sogning.og.filter.zip)

**Comment by mtolbol** [comment]
@koppen samme problem igen, som nævnt i #30 og #31 

På den "gamle" annoncer, virker søgebar og kategorier nu, men når der oprettes en ny fungerer det forsat ikke. Har forsøgt at optage fejlen via skærmoptaglese, men kan kun finde ud af at uploade som .zip :/

Men der er i hvert fald forsat et problem her - jeg kan ikke lige gennemskue hvad der skaber problemet.

**Comment by koppen** [comment]
Nu tror jeg, det er på plads; hvertfald har jeg oprettet et par nye annoncer og de er begge dukket op i søgningen bagefter.

Vær opmærksom på, at der kan gå op til 10 minutter før søgeindekset bliver genbygget og i den periode kan man ikke finde nye eller ændrede listings ud fra de opdaterede data.
