### ISSUE TITLE
Slet linje 1620 i koden

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#43]
Under "Inviter ven" ønsker vi at slette den 2. rubrik: "add_lots_of_email_addresses: "Hvis du planlægger at sende mange invitationer, skal du bruge et e-mail værktøj. Tjek %{this_article_link} for at finde informationer omkring egnede e-mail tjenester."

Som har linje 1620 i koden.

Jeg er usikker på hvorvidt vi bare kan slette denne linje, eller om du skaber nogle issues. I så fald må den gerne slettes.

![Skærmbillede 2019-07-30 kl  16 55 21](https://user-images.githubusercontent.com/44906533/62140382-318e9f80-b2eb-11e9-940e-03e45c16d6d4.png)

**Comment by koppen** [comment]
> Jeg er usikker på hvorvidt vi bare kan slette denne linje, eller om du skaber nogle issues.

Det ville skabe issues. I kunne måske bare fjerne teksten, så der stod

    add_lots_of_email_addresses: ""

men det kunne også give issues - det ville dog nok være visuelle issues, dog. Det sagt, så vises teksten kun til admins, så man kunne nok leve med det ;)

**Comment by mtolbol** [comment]
@koppen hvis teksten kun er synlig for admin har det ingen betydning.
