### ISSUE TITLE
Deploy ændring til 2-split bar

### ISSUE THREAD

**Issue by mtolbol** [mtolbol/sharetribe#48]
Vi har fået udviklet split-søgebar, med geografisk filtrering. Denne skulle være klar til deploy.

Vi har lovet udvikleren at vi ikke deployer til et offentligt repository

Herudover skriver han:
"please make sure to restart and  re-indexing search before testing"

Vi skal prøve og deploye og teste denne løsning

**Comment by koppen** [comment]
We receive a HTTP 500 when we search for anything location-based:

```
{"method":"GET","path":"/s","format":"html","controller":"HomepageController","action":"index","status":500,"error":"NameError: uninitialized constant ListingIndexService::Search::SphinxAdapter::Geocoder","duration":71.29,"view":0.0,"db":14.22,"params":{"q":"","location":"odense","lat":"","lng":""},"host":"www.tumlino.dk","community_id":1,"current_user_id":"AW-M5s9wb8zzHStvHCCfUQ","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0","referer":"https://www.tumlino.dk/","forwarded_for":"128.76.62.218","request_uuid":"f4a3aa55-cdff-473c-a756-8d9001c390b6"}

NameError (uninitialized constant ListingIndexService::Search::SphinxAdapter::Geocoder):
```

**Comment by koppen** [comment]
Det ser ud til at fungere nu: https://www.tumlino.dk/s?view=grid&q=&location=Kolding%2C+Danmark&lat=&lng=&price_min=0&price_max=100000
