### ISSUE TITLE
Google maps integration

### ISSUE THREAD

**Issue by koppen** [mtolbol/sharetribe#8]
Integration til Google maps er ikke opsat. Det er ikke muligt at oprette annoncer med angivelse af by / lokation. 

![billede](https://user-images.githubusercontent.com/6480/58025852-9a041800-7b15-11e9-9f92-2cd4f1decf74.png)

**Comment by koppen** [comment]
Hm, denne burde være på plads, og kortet kommet også frem nu. MEN der kommer til gengæld en fejlbesked i konsollen:

> Geocoding Service: This API project is not authorized to use this API.  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

Det lugter af, at der er hul igennem til Google Maps, men at vi skal aktivere et eller andet derinde.

**Comment by koppen** [comment]
@mtolbol Har du en Google-konto af en eller anden art, som jeg kan invitere til Tumlino-projektet i Google Developer Console?

**Comment by koppen** [comment]
Aha, fandt den. API-nøglen manglede adgang til Geocoding API'et, selv om det var enabled på projektet.

**Comment by mtolbol** [comment]
Hej Jakob,
Google-konto:
mortenjr@gmail.com
